100 REM System Statements and Functions
110 QG$="tf"
130 GOSUB _init

300 GOSUB _title:ARGS "SET KEY REPEAT and GETKEYREPEAT"
305 KR = GETKEYREPEAT

310 GOSUB _output:ARGS LIST$(NEXT)
311 SET KEY REPEAT OFF
315 GOSUB _assert:ARGS "GETKEYREPEAT=0"

320 GOSUB _output:ARGS LIST$(NEXT)
321 SET KEY REPEAT ON
325 GOSUB _assert:ARGS "GETKEYREPEAT=-1"

330 GOSUB _output:ARGS LIST$(NEXT)
331 SET KEY REPEAT OFF
335 GOSUB _assert:ARGS "GETKEYREPEAT=0"

340 IF KR THEN SET KEY REPEAT ON

