100 REM USE CHRSET and GETCHRSET Test/Demo
110 GOSUB _pchrset:PRINT LIST$(NEXT)
115 USE CHRSET 1
120 GOSUB _pchrset:PRINT LIST$(NEXT)
125 USE CHRSET 0
130 GOSUB _pchrset:PRINT LIST$(NEXT)
135 USE CHRSET "/demos/charmaps/charmaps/bold.chr"
140 GOSUB _pchrset:PRINT LIST$(NEXT)
145 USE CHRSET 0
150 GOSUB _pchrset:END
190 _pchrset:PRINT "CHRSET =";GETCHRSET:RETURN
